### ISSUE TITLE
mod spams log

### ISSUE THREAD

**Issue by Sneakometer** [CaelTheColher/Capes#22]
Using the mod with optifine pre 22 1.17.
It spams the log with the following exception:

```
java.io.FileNotFoundException: minecraft:capeof/yxff
	at net.minecraft.class_3294.method_14486(class_3294.java:67) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_3304.method_14486(class_3304.java:62) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:117) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:87) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:40) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:136) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:97) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:168) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.optifine.player.CapeUtils.downloadCape(CapeUtils.java:39) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_742.<init>(class_742.java:74) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_745.<init>(class_745.java:14) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_634.method_11097(class_634.java:470) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_2613.method_11235(class_2613.java:52) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_2613.method_11054(class_2613.java:10) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:38) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) [Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:193) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:158) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:135) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1077) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
```
Capes 1.2.2
Java 16.0.1 AdoptOpenJDK

**Comment by CaelTheColher** [comment]
Ironically enough this mod doesn't support optifine. Its made mainly so players can use Sodium and still have their optifine cape
